### ISSUE TITLE
Exit (1) with no log

### ISSUE THREAD

**Issue by pokapow** [TeDomum/docker-peertube#3]
When configure and run docker-compose, when try to run the compose, db container is ok, but peertube container can't start, exit(1) with no log:

`/opt/docker/peertube# docker-compose up`
```
Creating network "peertube_default" with the default driver
Creating peertube_peertube_1 ... done
Creating peertube_db_1       ... done
Attaching to peertube_peertube_1, peertube_db_1
db_1        | 2018-01-25 04:27:10.649 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1        | 2018-01-25 04:27:10.649 UTC [1] LOG:  listening on IPv6 address "::", port 5432
peertube_1  | Traceback (most recent call last):
peertube_1  |   File "/start.py", line 10, in <module>
peertube_1  |     convert("/conf/production.yaml", "/app/config/production.yaml", os.environ)
peertube_1  |   File "/start.py", line 7, in <lambda>
peertube_1  |     convert = lambda src, dst, args: open(dst, "w").write(jinja2.Template(open(src).read()).render(**args))
peertube_1  | IOError: [Errno 13] Permission denied: '/app/config/production.yaml'
db_1        | 2018-01-25 04:27:10.761 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1        | 2018-01-25 04:27:10.904 UTC [23] LOG:  database system was shut down at 2018-01-25 04:26:35 UTC
db_1        | 2018-01-25 04:27:10.977 UTC [1] LOG:  database system is ready to accept connections
peertube_peertube_1 exited with code 1
```

**Comment by pokapow** [comment]
```
docker logs 1c3cede1ecba
Traceback (most recent call last):
  File "/start.py", line 10, in <module>
    convert("/conf/production.yaml", "/app/config/production.yaml", os.environ)
  File "/start.py", line 7, in <lambda>
    convert = lambda src, dst, args: open(dst, "w").write(jinja2.Template(open(src).read()).render(**args))
IOError: [Errno 13] Permission denied: '/app/config/production.yaml'
```

**Comment by kaiyou** [comment]
Yes, a simple permission issue due to the privilege drop. I'll fix it tonight. Still, keep in mind that this image is temporary as most of the work is being merged in the official Peertube repo
